feat: add GitHub Actions workflow for continuous deployment to server.

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -14,7 +14,7 @@ jobs:
       - name: Deploy via SSH
         run: |
           echo "🔐 Creating SSH key..."
-          echo "${{ secrets.AWS_FREE }}" > key.pem
+          printf "%s" "${{ secrets.AWS_FREE }}" > key.pem
           chmod 600 key.pem
           ls -l key.pem
 
@@ -24,10 +24,16 @@ jobs:
             echo "🚀 Connected to VM"
 
             echo "📁 Moving to project directory..."
-            cd DevOps-Practice || { echo "❌ Failed to cd"; exit 1; }
+            cd /home/ubuntu/DevOps-Practice || { echo "❌ Failed to cd"; exit 1; }
 
-            echo "📥 Pulling latest code..."
-            git pull || { echo "❌ Git pull failed"; exit 1; }
+            echo "📥 Syncing latest code..."
+            git fetch origin
+            git reset --hard origin/main || { echo "❌ Git sync failed"; exit 1; }
+
+            echo "🟢 Loading Node version..."
+            export NVM_DIR="$HOME/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+            nvm use v22.22.1 || { echo "❌ NVM failed"; exit 1; }
 
             echo "📦 Installing dependencies..."
             pnpm install || { echo "❌ pnpm install failed"; exit 1; }
@@ -36,9 +42,7 @@ jobs:
             pnpm run build || { echo "❌ Build failed"; exit 1; }
 
             echo "♻️ Restarting PM2 services..."
-            pm2 restart http || pm2 start http
-            pm2 restart ws || pm2 start ws
-            pm2 restart nextjs-app || pm2 start nextjs-app
+            pm2 reload all || { echo "❌ PM2 reload failed"; exit 1; }
 
             echo "💾 Saving PM2 state..."
             pm2 save
