feat: Add GitHub Actions workflow for continuous deployment via SSH.

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -13,20 +13,38 @@ jobs:
     steps:
       - name: Deploy via SSH
         run: |
+          echo "🔐 Creating SSH key..."
           echo "${{ secrets.AWS_FREE }}" > key.pem
           chmod 600 key.pem
-          
+          ls -l key.pem
+
+          echo "🌐 Connecting to server..."
           ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
-            cd /DevOps-Practice && git pull
-
-            nvm use v22.22.1
-
-            pnpm install
-            pnpm run build
             
+            echo "🚀 Connected to VM"
+
+            echo "📁 Moving to project directory..."
+            cd /DevOps-Practice || { echo "❌ Failed to cd"; exit 1; }
+
+            echo "📥 Pulling latest code..."
+            git pull || { echo "❌ Git pull failed"; exit 1; }
+
+            echo "🟢 Loading Node version..."
+            nvm use v22.22.1 || { echo "❌ NVM failed"; exit 1; }
+
+            echo "📦 Installing dependencies..."
+            pnpm install || { echo "❌ pnpm install failed"; exit 1; }
+
+            echo "🏗️ Building project..."
+            pnpm run build || { echo "❌ Build failed"; exit 1; }
+
+            echo "♻️ Restarting PM2 services..."
             pm2 restart http || pm2 start http
             pm2 restart ws || pm2 start ws
             pm2 restart nextjs-app || pm2 start nextjs-app
-            
+
+            echo "💾 Saving PM2 state..."
             pm2 save
+
+            echo "✅ Deployment finished successfully!"
           EOF
